version: "3"

services:
  cach:
    restart: always
    image: memcached

  web:
    restart: always
    depends_on: cach
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5000"

