version: "3"

services:
  cach:
    restart: always
    image: memcached
    ports:
      - "11211:11211"

  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5000"

